### ISSUE TITLE
Requiring library does not work

### ISSUE THREAD

**Issue by rgalanakis** [TeleSign/ruby_telesign#5]
I get an error, due to the `require './lib/rest.rb'` line. I'm no Ruby expert but I think you want `require 'telesign/rest'`, which is how I see it done in other gems.

```
cannot load such file -- ./lib/rest.rb
	/Users/rgalanakis/.rbenv/versions/2.2.0/gemsets/cozy-support/gems/telesign-1.0.0/lib/telesign.rb:11:in `require'
	/Users/rgalanakis/.rbenv/versions/2.2.0/gemsets/cozy-support/gems/telesign-1.0.0/lib/telesign.rb:11:in `<top (required)>'
```

**Comment by jarradsl** [comment]
Thanks for letting us know! It was still set for local development. This has been fixed in v1.0.1.
